#!/usr/bin/env ruby
require 'optparse'

opts = OptionParser.new
opts.on('--noop', 'dry-run mode') { |v| $noop = true }
opts.parse!

`git branch -r`.each_line do |branch|
  branch.strip!.chomp!
  next if branch =~ %r![^/]+/main!
  next if branch =~ %r![^/]+/develop!

  branch.gsub!(%r!\(!, '\(')
  branch.gsub!(%r!\)!, '\)')
  if `git branch --contains #{branch}`.each_line.any? { |included| included.strip.chomp =~ /\A[* ]*(develop|main)\z/ }
    ref = branch.sub(%r!^([^/]+)/!, '')
    command = "git push --delete #{$1} #{ref}"
    puts command
    unless $noop
      system command
    end
  end
end
